---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # Ensure that the code in repository actually follows the .editconfig rules
  # If this check disagrees with another, stricter, check (_.e.g_ it complains
  # about the code formatted by clang-format), exclude the problem files with the
  # `--exclude` flag. It accepts a regex that should match all the files you want to
  # exclude. For example:
  #
  #   args: ["--exclude", "^some-file|*\\.some-extension"]
  #
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.0"
    hooks:
      - id: editorconfig-checker


  #
  # Text Markup Linters and Formatters
  #

  # To add a table of contents to your markdown files (generated by mdformat-toc), add
  # the following snippet where you want the toc
  #
  # <!-- mdformat-toc start --slug=gitlab --no-anchors --maxlevel=4 --minlevel=2 -->
  #
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-frontmatter
          - mdformat-toc

  - repo: https://github.com/dzhu/rstfmt.git
    rev: v0.0.14
    hooks:
      - id: rstfmt
        args: ["--width", "0"]  # We don't want to hard-wrap lines

  # Spell-check prose and code.
  # See https://github.com/crate-ci/typos/blob/master/docs/reference.md
  #
  # To disable the check for a specific file or folder, use
  #
  #   args: ["--force-exclude", "--exclude", "relative-path-to-file"]
  #
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.12.4
    hooks:
      - id: typos

  #
  # Python Linters and Formatters
  #

  # Format the code with black
  #
  # We could use ruff to format the code as well but the output it produces is slightly
  # different to the output that black produces. Until ruff is as well integrated in the
  # ecosystem we'll stick with black.
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Run `black` on code contained in python docstrings and `.rst` code blocks.
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  # Create a [tool.ruff.lint] block in your `pyproject.toml` file to configure
  # these checks. If you are not in a python package, create a `.flake8` file
  # in the root of your repository.
  #
  # In the default configuration we ignore errors which make development of
  # one-off scripts too painful. You should remove these rules if you have a
  # `pyproject.toml` file
  #
  # - G004: Logging statement uses f-string
  # - S***: subprocess call, use of assert, ...
  # - T201: Print found

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix", "--unsafe-fixes", "--config", "lint.ignore=['G004','S','T201']"]


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  #
  # Linters for docker compose files
  #

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  #
  # Python-specific Linters
  #

  # Mypy needs to be run as a local hook since it needs access to the types of
  # the dependencies we install.
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --non-interactive
        language: system
        types: [python]
        exclude: "tests/"
        require_serial: true
